export const videos = [
  {
    id: "1",
    uri: require("@/assets/videos/video1.mp4"),
    author: "Nile Red",
    title: "Making hydrogen and oxygen bubbles",
    avatar:
      "https://yt3.ggpht.com/sJjv-k8rR1lggpulNcj5jLN7Cgf7_6Hzjkp0_93cy2xvEAjgcE8hXJUxx0vaKrVXYthJMKsg=s176-c-k-c0x00ffffff-no-rj-mo",
    description: "Making hydrogen and oxygen bubble",
    hashtags: "#Hydrogen #Oxygen",
    datePosted: "12 hours ago",
    likes: 2600000,
    comments: 21000,
    bookmarks: 1583,
    shares: 12000,
  },
  {
    id: "2",
    uri: require("@/assets/videos/video2.mp4"),
    author: "Sam Milton",
    description: "Rayar el palo is a unique sport in",
    hashtags: "#Unique #RayarPalo",
    datePosted: "3 hours ago",
    likes: 150000,
    comments: 829,
    bookmarks: 375,
    shares: 1300,
  },
  {
    id: "3",
    uri: require("@/assets/videos/video3.mp4"),
    author: "Author4",
    description: "This is a sample description for video 3",
    hashtags: "#cool #videolar",
    datePosted: "3 hours ago",
    likes: 5000,
    comments: 93,
    bookmarks: 32,
    shares: 300,
  },
  {
    id: "4",
    uri: require("@/assets/videos/video4.mp4"),
    author: "Author4",
    description: "This is a sample description for video 4",
    hashtags: "#cool #videolar",
    datePosted: "3 hours ago",
    likes: 9842,
    comments: 251,
    bookmarks: 95,
    shares: 923,
  },
  {
    id: "5",
    uri: require("@/assets/videos/video5.mp4"),
    author: "Author5",
    description: "This is a sample description for video 5",
    hashtags: "#cool #videolar",
    datePosted: "3 hours ago",
    likes: 10293,
    comments: 731,
    bookmarks: 151,
    shares: 1592,
  },
];
