/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: fletcherkinnear (https://sketchfab.com/fletcherkinnear)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/saumurai-150603038ee6476a9a4b173c682ff8d5
Title: Saumurai
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/native";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Head_Head_0: THREE.Mesh;
    Head_Eyelashes_0: THREE.Mesh;
    Teeth_Bottom_Face_0: THREE.Mesh;
    Tongue_Face_0: THREE.Mesh;
    Shoulder_Plates_Body_0: THREE.Mesh;
    Teeth_Top_Face_0: THREE.Mesh;
    Leg_Plates_Rear_Body_0: THREE.Mesh;
    Torso_Body_0: THREE.Mesh;
    Torso_Rope_0: THREE.Mesh;
    Leg_Plates_Groin_Body_0: THREE.Mesh;
    Mane_Fur_0: THREE.Mesh;
    Kabuto_Body_0: THREE.Mesh;
    Chinstrap_Body_0: THREE.Mesh;
    Chinstrap_Rope_0: THREE.Mesh;
    Arms_Body_0: THREE.Mesh;
    Arms_Rope_0: THREE.Mesh;
    Legs_Body_0: THREE.Mesh;
    Legs_Rope_0: THREE.Mesh;
    Cloth_Shirt_Body_0: THREE.Mesh;
    Leg_Plates_Sides_Body_0: THREE.Mesh;
    Eyes_Outer_Eyes_Outer_0: THREE.Mesh;
    Eyes001_Eyes_0: THREE.Mesh;
  };
  materials: {
    Head: THREE.MeshStandardMaterial;
    Eyelashes: THREE.MeshStandardMaterial;
    Face: THREE.MeshStandardMaterial;
    Body: THREE.MeshStandardMaterial;
    Rope: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    Eyes_Outer: THREE.MeshStandardMaterial;
    Eyes: THREE.MeshStandardMaterial;
  };
};

export default function SamuraiModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    require("../../assets/3d-assets/samurai-small.glb")
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        rotation={[-Math.PI / 2, 0, 0.2]}
        scale={0.0105}
        position={[0, -12, 0]}
      >
        <group position={[0, -0.361, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Head_Head_0.geometry}
            material={materials.Head}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Head_Eyelashes_0.geometry}
            material={materials.Eyelashes}
          />
        </group>
        <group position={[0, -88.355, 1542.606]} scale={[0.945, 0.863, 0.7]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teeth_Bottom_Face_0.geometry}
            material={materials.Face}
            position={[0, 3.56, 13.706]}
          />
        </group>
        <group position={[0, -88.355, 1542.606]} scale={[0.945, 0.863, 0.7]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teeth_Top_Face_0.geometry}
            material={materials.Face}
            position={[0, 3.56, 13.706]}
          />
        </group>
        <group position={[-5.066, 293.883, 1324.64]} scale={[0.806, 0.6, 2.15]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mane_Fur_0.geometry}
            material={materials.material}
            position={[4.647, -77.273, 83.253]}
          />
        </group>
        <group position={[-2.676, 12.798, 1709.985]} scale={0.982}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Kabuto_Body_0.geometry}
            material={materials.Body}
            position={[2.726, -18.504, -1709.688]}
          />
        </group>
        <group position={[0, -17.856, 1555.494]}>
          <group position={[0, 17.856, -1557.664]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Chinstrap_Body_0.geometry}
              material={materials.Body}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Chinstrap_Rope_0.geometry}
              material={materials.Rope}
            />
          </group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tongue_Face_0.geometry}
          material={materials.Face}
          position={[-0.5, -73.174, 1536.701]}
          scale={[1.199, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shoulder_Plates_Body_0.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leg_Plates_Rear_Body_0.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torso_Body_0.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torso_Rope_0.geometry}
          material={materials.Rope}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leg_Plates_Groin_Body_0.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arms_Body_0.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arms_Rope_0.geometry}
          material={materials.Rope}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Legs_Body_0.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Legs_Rope_0.geometry}
          material={materials.Rope}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cloth_Shirt_Body_0.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leg_Plates_Sides_Body_0.geometry}
          material={materials.Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Eyes_Outer_Eyes_Outer_0.geometry}
          material={materials.Eyes_Outer}
          position={[0, -90.982, 1613.534]}
          scale={0.1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Eyes001_Eyes_0.geometry}
          material={materials.Eyes}
          position={[0, -90.982, 1613.534]}
          rotation={[-0.034, 0, 0]}
          scale={0.1}
        />
      </group>
    </group>
  );
}

useGLTF.preload(require("../../assets/3d-assets/samurai-small.glb"));
